"""Train the main EPA model and report evaluation alongside baselines.

This script is the main training entry point::

    python -m src.models.train \
        --data data/processed/examples.csv \
        --model_out models/epa_model.joblib

It produces:

* the saved sklearn ``Pipeline`` (TF-IDF + structured features + LR),
* a Markdown evaluation report under ``reports/`` with overall metrics,
  per-scenario breakdown, threshold sweep, and baseline comparison.
"""
from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path
from typing import Any, Dict, List, Optional

import joblib
import numpy as np
import pandas as pd

from src.models.baselines import ClassPriorBaseline, EveryRecipientBaseline
from src.models.metrics import (
    compute_metrics,
    evaluate_scenarios,
    threshold_sweep,
)
from src.models.pipeline import build_pipeline
from src.models.split import assert_no_group_leakage, group_train_test_split
from src.utils.io import ensure_dir, load_config, setup_logging

logger = logging.getLogger(__name__)


def _read_examples(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path)
    # Defensive defaults: ensure expected columns exist.
    for col, default in [
        ("subject", ""),
        ("body", ""),
        ("task", ""),
        ("full_context", ""),
        ("candidate_email", ""),
        ("candidate_name", ""),
        ("sender_email", ""),
        ("sender_name", ""),
        ("candidate_role", ""),
    ]:
        if col not in df.columns:
            df[col] = default
        df[col] = df[col].fillna(default).astype(str)
    for col in [
        "is_sender",
        "is_to",
        "is_cc",
        "num_to_recipients",
        "num_cc_recipients",
        "num_total_candidates",
        "no_one_responsible",
        "label",
    ]:
        if col not in df.columns:
            df[col] = 0
        df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0).astype(int)

    if "full_context" in df.columns and df["full_context"].str.len().sum() == 0:
        df["full_context"] = (
            df["subject"].astype(str)
            + " [SEP] "
            + df["task"].astype(str)
            + " [SEP] "
            + df["body"].astype(str)
        )
    return df


def _format_metrics_block(name: str, m: Dict[str, Any]) -> str:
    keys = ["precision", "recall", "f1", "accuracy", "pr_auc", "roc_auc", "tp", "fp", "fn", "tn", "n"]
    lines = [f"### {name}"]
    for k in keys:
        if k in m:
            v = m[k]
            if isinstance(v, float):
                lines.append(f"- **{k}**: {v:.4f}")
            else:
                lines.append(f"- **{k}**: {v}")
    return "\n".join(lines)


def _df_to_md(df: pd.DataFrame, max_rows: int = 50) -> str:
    if len(df) == 0:
        return "_(no rows)_"
    df = df.head(max_rows)
    return df.to_markdown(index=False, floatfmt=".4f")


def write_report(
    out: Path,
    cfg: Dict[str, Any],
    overall: Dict[str, Any],
    baselines: Dict[str, Dict[str, Any]],
    scenarios: pd.DataFrame,
    sweep: pd.DataFrame,
) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    parts: List[str] = []
    parts.append("# EPA evaluation report\n")
    parts.append(
        "Auto-generated by `src.models.train`. Numbers are computed on the "
        "held-out test split using the configured threshold "
        f"(`{cfg['evaluation']['default_threshold']}`).\n"
    )

    parts.append("## Main model — Logistic Regression with handcrafted + TF-IDF features\n")
    parts.append(_format_metrics_block("Held-out test set", overall))

    parts.append("\n## Baselines\n")
    for name, m in baselines.items():
        parts.append(_format_metrics_block(name, m))
        parts.append("")

    parts.append("\n## Scenario breakdown\n")
    parts.append(
        "Slices that mirror the paper's discussion of single- vs. "
        "multi-recipient performance, plus addressee-tagging cases the "
        "take-home asked us to look at explicitly.\n"
    )
    parts.append(_df_to_md(scenarios[
        [c for c in [
            "scenario", "n_examples", "support_pos", "support_neg",
            "precision", "recall", "f1", "pr_auc",
        ] if c in scenarios.columns]
    ]))

    parts.append("\n## Threshold sweep\n")
    parts.append(_df_to_md(sweep[
        [c for c in ["threshold", "precision", "recall", "f1", "accuracy"] if c in sweep.columns]
    ]))

    out.write_text("\n".join(parts), encoding="utf-8")
    logger.info("Wrote evaluation report to %s", out)


def main(argv: Optional[List[str]] = None) -> int:
    setup_logging()
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", default="config.yaml")
    parser.add_argument("--data", default=None)
    parser.add_argument("--model_out", default=None)
    parser.add_argument("--report_out", default=None)
    args = parser.parse_args(argv)

    cfg = load_config(args.config)
    data_path = Path(args.data or cfg["paths"]["examples_csv"])
    model_out = Path(args.model_out or cfg["paths"]["model_path"])
    report_out = Path(args.report_out or Path(cfg["paths"]["reports_dir"]) / "evaluation.md")

    df = _read_examples(data_path)
    if len(df) == 0:
        raise SystemExit(f"No examples found in {data_path}")

    logger.info(
        "Loaded %d candidate rows (%d positive, prior=%.4f)",
        len(df),
        int(df["label"].sum()),
        df["label"].mean(),
    )

    train_df, val_df, test_df = group_train_test_split(
        df,
        group_key=cfg["split"]["group_key"],
        test_size=cfg["split"]["test_size"],
        val_size=cfg["split"]["val_size"],
        random_state=cfg["split"]["random_state"],
    )
    assert_no_group_leakage(train_df, val_df, test_df, group_key=cfg["split"]["group_key"])
    logger.info(
        "Group split sizes: train=%d val=%d test=%d", len(train_df), len(val_df), len(test_df)
    )

    y_train = train_df["label"].to_numpy()
    y_test = test_df["label"].to_numpy()

    pipe, _ = build_pipeline(cfg)
    pipe.fit(train_df, y_train)

    threshold = float(cfg["evaluation"]["default_threshold"])
    y_score = pipe.predict_proba(test_df)[:, 1]
    y_pred = (y_score >= threshold).astype(int)

    overall = compute_metrics(y_test, y_pred, y_score)

    # Baselines.
    baselines: Dict[str, Dict[str, Any]] = {}
    every = EveryRecipientBaseline().fit(train_df, y_train)
    every_pred = every.predict(test_df)
    every_score = every.predict_proba(test_df)[:, 1]
    baselines["Every-recipient baseline"] = compute_metrics(y_test, every_pred, every_score)

    prior = ClassPriorBaseline().fit(train_df, y_train)
    prior_pred = prior.predict(test_df, threshold=threshold)
    prior_score = prior.predict_proba(test_df)[:, 1]
    baselines["Class-prior baseline (p=%.3f)" % prior.prior_] = compute_metrics(
        y_test, prior_pred, prior_score
    )

    # Scenario breakdown.
    scenarios = evaluate_scenarios(test_df, y_test, y_pred, y_score)

    # Threshold sweep.
    sweep = threshold_sweep(y_test, y_score, list(cfg["evaluation"]["threshold_grid"]))

    # Persist the model.
    ensure_dir(model_out.parent)
    joblib.dump(
        {
            "pipeline": pipe,
            "config": cfg,
            "feature_columns": list(test_df.columns),
            "default_threshold": threshold,
            "training_class_prior": float(prior.prior_),
        },
        model_out,
    )
    logger.info("Saved model to %s", model_out)

    # Persist the report.
    write_report(report_out, cfg, overall, baselines, scenarios, sweep)

    # Also drop a JSON summary next to the report for programmatic consumers.
    summary = {
        "overall": overall,
        "baselines": baselines,
        "scenarios": scenarios.to_dict(orient="records"),
        "threshold_sweep": sweep.to_dict(orient="records"),
        "training_class_prior": float(prior.prior_),
        "n_train": len(train_df),
        "n_val": len(val_df),
        "n_test": len(test_df),
    }
    json_path = report_out.with_suffix(".json")
    json_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    logger.info("Wrote summary JSON to %s", json_path)
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
